name: "CI"

on:
  push:
    branches:
      - master
    paths:
      - "**.html"
    
jobs:
  copy_whatsnew:
    runs-on: ubuntu-latest
    steps:
      - name: "Copy What's new *.html files to felisdiligens.github.io"
        uses: "nkoppel/push-files-to-another-repository@master"
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: "whatsnew.html whatsnewdark.html"
          destination-username: 'FelisDiligens'
          destination-repository: 'felisdiligens.github.io'
          destination-directory: 'Fo76ini/'
          destination-branch: master
          commit-email: '47528453+FelisDiligens@users.noreply.github.com'
