name: "Main Workflow"

on:
  push:
    branches:
    - master
    
jobs:
  copy_whatsnew:
    runs-on: ubuntu-latest
    steps:
      - name: "Copy What's new *.html files to felisdiligens.github.io"
        uses: "nkoppel/push-files-to-another-repository@master"
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: "\"What's new.html\" \"What's new - Dark.html\""
          destination-username: 'FelisDiligens'
          destination-repository: 'felisdiligens.github.io'
          destination-directory: 'Fo76ini/'
          commit-email: '47528453+FelisDiligens@users.noreply.github.com'
